SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE ACCOUNT
(
	MSISDN VARCHAR(30) NOT NULL,
	SERVICE_ID INT NOT NULL,
	TELCO_ID INT NOT NULL,
	REGISTER_TIME DATETIME NOT NULL,
	PRIMARY KEY (MSISDN, SERVICE_ID)
);


CREATE TABLE CAMPAIGN_PROMOTE
(
	PID INT NOT NULL AUTO_INCREMENT,
	PUBLISHER_ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	-- 0-100
	DIAL_CONFIG INT NOT NULL COMMENT '0-100',
	DIAL_COUNT INT NOT NULL,
	DIAL_SHOOT INT NOT NULL,
	PRIMARY KEY (PID)
);


CREATE TABLE CAMPAIGN_PROMOTE_SERVICE_MAP
(
	PID INT NOT NULL,
	SERVICE_ID INT NOT NULL
);


CREATE TABLE PARTNER_GATEWAY
(
	PARTNER_GW_ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	USERNAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PRIMARY KEY (PARTNER_GW_ID)
);


CREATE TABLE PUBLISHER
(
	PUBLISHER_ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100),
	PRIMARY KEY (PUBLISHER_ID)
);


CREATE TABLE QUIT_LOG
(
	MSISDN VARCHAR(30) NOT NULL,
	SERVICE_ID INT NOT NULL,
	TELCO_ID INT NOT NULL,
	REGISTER_TIME DATETIME NOT NULL,
	QUIT_TIME DATETIME NOT NULL
);


CREATE TABLE RINGTONE_PARAMS
(
	TRACK_ID BIGINT NOT NULL,
	PRIMARY KEY (TRACK_ID)
);


CREATE TABLE SERVICE
(
	SERVICE_ID INT NOT NULL AUTO_INCREMENT,
	SHORTCODE VARCHAR(20) NOT NULL,
	KEYWORD VARCHAR(10) NOT NULL,
	PRIMARY KEY (SERVICE_ID)
);


CREATE TABLE SUBSCRIBER_DN
(
	SUB_DN_ID VARCHAR(50) NOT NULL,
	PARTNER_GW_ID INT NOT NULL,
	PARTNER_GW_TXID VARCHAR(100) NOT NULL,
	CMD ENUM('REG','UNREG') NOT NULL,
	SHORTCODE VARCHAR(20),
	KEYWORD VARCHAR(10),
	MSISDN VARCHAR(30) NOT NULL,
	TELCO_ID INT NOT NULL,
	RESPONSE_DATA TEXT NOT NULL,
	SYS_TIME DATETIME NOT NULL,
	RESPONSE_TIME DATETIME NOT NULL,
	PRIMARY KEY (SUB_DN_ID),
	UNIQUE (PARTNER_GW_TXID, PARTNER_GW_ID)
);


CREATE TABLE TELCO
(
	TELCO_ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (TELCO_ID)
);


CREATE TABLE TRACK_ENTY
(
	TRACK_ID BIGINT NOT NULL,
	PARENT_ID BIGINT,
	PID INT,
	SHORTCODE VARCHAR(20) NOT NULL,
	KEYWORD VARCHAR(10) NOT NULL,
	MSISDN VARCHAR(20) NOT NULL,
	TELCO_ID INT NOT NULL,
	SYS_TIME DATETIME NOT NULL,
	-- 0:expried (not register)
	-- 1:register
	-- 2:shoot pexel
	STATUS TINYINT(3) COMMENT '0:expried (not register)
1:register
2:shoot pexel',
	PRIMARY KEY (TRACK_ID)
);


CREATE TABLE TRACK_ENTY_PENDING
(
	TRACK_ID BIGINT NOT NULL AUTO_INCREMENT,
	PARENT_ID BIGINT,
	PID INT,
	SHORTCODE VARCHAR(20) NOT NULL,
	KEYWORD VARCHAR(10) NOT NULL,
	MSISDN VARCHAR(20) NOT NULL,
	TELCO_ID INT,
	SYS_TIME DATETIME NOT NULL,
	PRIMARY KEY (TRACK_ID)
);



/* Create Foreign Keys */

ALTER TABLE CAMPAIGN_PROMOTE_SERVICE_MAP
	ADD FOREIGN KEY (PID)
	REFERENCES CAMPAIGN_PROMOTE (PID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRACK_ENTY
	ADD FOREIGN KEY (PID)
	REFERENCES CAMPAIGN_PROMOTE (PID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRACK_ENTY_PENDING
	ADD FOREIGN KEY (PID)
	REFERENCES CAMPAIGN_PROMOTE (PID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SUBSCRIBER_DN
	ADD FOREIGN KEY (PARTNER_GW_ID)
	REFERENCES PARTNER_GATEWAY (PARTNER_GW_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAMPAIGN_PROMOTE
	ADD FOREIGN KEY (PUBLISHER_ID)
	REFERENCES PUBLISHER (PUBLISHER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACCOUNT
	ADD FOREIGN KEY (SERVICE_ID)
	REFERENCES SERVICE (SERVICE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CAMPAIGN_PROMOTE_SERVICE_MAP
	ADD FOREIGN KEY (SERVICE_ID)
	REFERENCES SERVICE (SERVICE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIT_LOG
	ADD FOREIGN KEY (SERVICE_ID)
	REFERENCES SERVICE (SERVICE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACCOUNT
	ADD FOREIGN KEY (TELCO_ID)
	REFERENCES TELCO (TELCO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIT_LOG
	ADD FOREIGN KEY (TELCO_ID)
	REFERENCES TELCO (TELCO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SUBSCRIBER_DN
	ADD FOREIGN KEY (TELCO_ID)
	REFERENCES TELCO (TELCO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRACK_ENTY
	ADD FOREIGN KEY (TELCO_ID)
	REFERENCES TELCO (TELCO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRACK_ENTY_PENDING
	ADD FOREIGN KEY (TELCO_ID)
	REFERENCES TELCO (TELCO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



